_core:
  default_config_hash: UvSCt3S_NldJPFzvhSNOy9vWoPPFhmsmTC12vtVss9s
langcode: en-gb
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/default/files/vagabondo-logo.svg
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: light_blue
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: vertical
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: default
show_description_toggle: false
show_user_theme_settings: false
